# Generated by Django 2.2.6 on 2020-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_apikey_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title', 'youtube_video_id'], name='videos_vide_title_15eb6f_idx'),
        ),
    ]
