version: '3'
    
services:
    redis:
        restart: always
        image: redis:latest
        expose:
          - "6379"
    web:
        build: .
        command: bash -c "python /code/manage.py collectstatic --no-input && /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        expose:
            - "8000"
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A tasks worker -l info
        volumes:
            - .:/code
        depends_on:
            - redis
    celery-beat:
        build: .
        command: celery -A tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        volumes:
            - .:/code
        depends_on:
            - redis